dist: trusty
language: c
notifications:
  email:
    - user.localhost2000@gmail.com

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libconfuse-dev libcunit1-dev libmsgpack-dev

compiler: gcc

script: autoreconf -i && ./configure && make && make test
